<a href="https://colab.research.google.com/github/tanvirshakil6059/CGCodeGenerator/blob/main/Mid_Assigment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **Midterm Assignment (PiP-A)**

 **Name: Md Tanvir Rahman Shakil**
 
 **ID: 18-36691-1**







**Problem #1**

In [ ]:
list1 = ["py", "i", "m", "favou", "lang"]
list2 = ["thon", "s", "y", "rite", "uage"]

def list_concate(list1,list2):
  new_list = [i + j for i, j in zip(list1,list2)]
  print ("Final list: "+str(new_list))

list_concate(list1,list2)

Final list: ['python', 'is', 'my', 'favourite', 'language']


**Problem #2**

In [142]:
import numpy

arr = numpy.array([[20 ,66, 88, 12], [75 ,19, 92, 71], [27 ,90, 33, 67], [21 ,14, 25, 38], [51 ,44, 57, 77]])

new_arr=arr[::2,1::2]

print(new_arr)

[[66 12]
 [90 67]
 [44 77]]


**Problem #3**

In [141]:
import numpy as np

arr = np.arange(10,34).reshape((8, 3))

x1, x2, x3, x4 = np.split(arr, 4)
print(x1)
print(x2)
print(x3)
print(x4)

[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]
[[22 23 24]
 [25 26 27]]
[[28 29 30]
 [31 32 33]]


**Problem #4**

In [184]:
import numpy as np

arr = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

arr_r=arr[:,arr[1,:].argsort()]

arr_c=arr[arr[:, 1].argsort()]

print("Original Array:" )
print(arr )

print("Sorting by 2nd row Array:" )
print(arr_r)

print("Sorting by 2nd column Array:" )
print(arr_c)

Original Array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting by 2nd row Array:
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting by 2nd column Array:
[[82 22 12]
 [34 43 73]
 [53 94 66]]


**Problem #5**

In [185]:
class Vehicle:
  def __init__(self,name,mileage,capacity):
    self.name=name
    self.mileage=mileage
    self.capacity=capacity
  
  def fare(self):
    return self.capacity*100

class Bus(Vehicle):
     
    def fare(self):
       return (self.capacity*100)+((self.capacity*100)*0.1)

class Minibus(Bus):
   
     def fare(self):
       return ((self.capacity*100)+((self.capacity*100)*0.1))*0.5

V = Vehicle('Premio',70,5)
B = Bus('Ena',80,50)
Mb= Minibus("Turag",60,20)

print('Fare Charge of Vehicle:',V.fare())
print('Fare Charge of Bus:',B.fare())
print('Fare Charge of Minibus:',Mb.fare())

Fare Charge of Vehicle: 500
Fare Charge of Bus: 5500.0
Fare Charge of Minibus: 1100.0


**Problem #6**

In [192]:
import keyword
Reserve_keywords= keyword.kwlist

def Check(Reserve_keywords):

  kw=input("Enter a keyword:")
  if kw in Reserve_keywords:
      print('The keyword is Reservekeywords')  
  else:
    print('The keyword is not Reserve keywords')
Check(Reserve_keywords)

Enter a keyword:if
The keyword is Reservekeywords


**Problem #7**